#!/bin/bash
for j in {1,2,4};
	do for i in {1..3};
		do /usr/bin/time -o time$i mpiexec -np $j bin/hpc_solver task5.txt;
	done &&  paste time1 time2 time3 > np$j && rm time1 time2 time3;
done
a=24
mv np1 np1el$a;
mv np2 np2el$a;
mv np4 np4el$a
